### ISSUE TITLE
Building the Python binding fails if radare2 is installed for user only (sys/user.sh)

### ISSUE THREAD

**Issue by v-p-b** [radareorg/radare2-bindings#122]
When installing radare2 with the `sys/user.sh` script libr headers aren't copied to the system directories (this is expected), so the build process of the Python binding (and possibly others) fails with messages similar to the following:

```
r_asm_wrap.cxx:3086:21: fatal error: r_diff.h: No such file or directory
  #include <r_diff.h>
```

This can be worked around by providing the `C_INCLUDE_PATH` and  `CPLUS_INCLUDE_PATH` environment variables for `make`:

```
C_INCLUDE_PATH=$C_INCLUDE_PATH:/path/to/radare2/libr/include/ CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:/path/to/radare2/libr/include/ PYTHON_CONFIG=python2.7-config make
```

I'm not sure if this should be handled by the the Makefiles, but a note in the README (or having this ticket as a clue) might be useful.

**Comment by radare** [comment]
Should use the info from pkgconfig,

**Comment by radare** [comment]
how are you compiling  the bindings? because if you use r2pm, the PKG_CONFIG_PATH should already be set to point to the home and this shouldnt be an issue at all

**Comment by v-p-b** [comment]
I'm building radare2-bindings "manually", according to the README.

I first tried to use the sys/python.sh script from radare2 but it failed, presumably because improper vala/valabind version, but I still have to double check that.

**Comment by radare** [comment]
the readme and sys/python.sh are suposed to be followed by users installing things in system. use r2pm from now on. all those scripts and instructions shuold be updated. or just use configure the pkg-config-path accordingly

**Comment by XVilka** [comment]
Should be fixed by now.
