### ISSUE TITLE
binding for python double free?

### ISSUE THREAD

**Issue by cherry-wb** [radareorg/radare2-bindings#123]
Hello everyone:

Is this a double free problem?
```
%extend RAnalBlock {
~RAnalBlock() {
r_anal_bb_free(self);
}
};
%extend RAnalOp {
~RAnalOp() {
r_anal_op_free(self);
}
};
%extend RAnalDiff {
~RAnalDiff() {
r_anal_diff_free(self);
}
};
%extend RAnalFunction {
std::vector get_bbs() {
std::vector ret;
RList list;
RListIter _iter;
RAnalBlock *item;
list = r_anal_fcn_get_bbs (self);
if (list)
for (iter = list->head; iter && (item = (RAnalBlock)iter->data); iter = iter->n)
ret.push_back(_item);
return ret;
}
```
The apis generated by valabind are as above, the returned std::vector obj in python is a shallow copy, so the objs pointed by pointers in the objs are not copyed, but when destroying, the de-constructer function will try to free memory regions that it does not own.
And this will cause a problem.
How can we solve this?

**Comment by radare** [comment]
Can you send a pr for valabind? But i guess the problem is in the vapi file, so probably the dblfree will be gone by fixing it.

For simplicity, stability, speed and maintainability i use to recommend r2pipe, but it will be good to give some love to the r2b swig bindings too.

**Comment by cherry-wb** [comment]
[r_anal.vapi.txt](https://github.com/radare/radare2-bindings/files/302002/r_anal.vapi.txt)

what do you mean for "a pr for valabind"?,this is the vapi file, how can i fix it?

**Comment by radare** [comment]
pr for valabind means pullrequest for https://github.com/radare/valabind

valabind parses the .vapi files (yes, r_anal.vapi in this case), and generates the `.i` (swig interface files) which are then processed by swig to generate cxx files which are compiled to load as python (or other) modules. that's how automatic binding generation is done.

The easiest way to solve this is by dropping the free statement, but this obviously creates a memleak. so i would suggest creating a small test case (or a bunch of them). to ensure that proper usage works and dblfree doesnt happens while fixing this issue.

**Comment by cherry-wb** [comment]
That's fine!
Thank you.

**Comment by XVilka** [comment]
Can be this closed?

**Comment by radare** [comment]
Nope. Problem is that swig and c dont have a way to specify ownership and some heaped structs are unowned by considered owned by swig so we need to have cloning helpers here and there or find a way to handle that ownership thing with accessors for all the fields like java does. So i prefer to stabilize core api before updating the bindings and making them accessible and r2pipe is still the best option for 90% of the usecases

**Comment by trufae** [comment]
we have proper python bindings now, closing here
