### ISSUE TITLE
Do not use valabind and swig for bindings at all

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2-bindings#179]
Abandon valabind and generate bindings directly from C headers of the radare2:

- [ ]  For generating Rust can be called  https://rust-lang-nursery.github.io/rust-bindgen/
- [ ]  For generating Go bindings can be used https://github.com/xlab/c-for-go
- [ ]  For generating Python bindings can be used https://github.com/trolldbois/ctypeslib
- [ ]  For generating Ruby bindings can be used https://github.com/neelance/ffi_gen
- [ ]  For generating Lua bindings can be used https://github.com/orangeduck/LuaAutoC
- [ ]  For generating Node FFI bindings can be used https://github.com/diosmosis/node-ffi-generator
- [ ]  For generating Haskell bindings can be used https://github.com/haskell/c2hs
- [ ]  Using GNAT to generate Ada bindings  https://www.adacore.com/gems/gem-59

So basicaly idea is to write a small wrapper which will call the respective binding generators, which are certainly better at their job and more actively maintained than valabind & swig. Moreover, it eliminates the need of `*.vapi` files or swig interfaces.

**Comment by XVilka** [comment]
Or using PyAutoC for Python https://github.com/orangeduck/PyAutoC ( see https://github.com/radare/radare2-bindings/issues/156 )

**Comment by Maijin** [comment]
@radare ^

**Comment by XVilka** [comment]
Done with Python and Rust (for now a bit hackish, but can be a base for extending: https://github.com/XVilka/r2bindgen

**Comment by radare** [comment]
I dont think we should kill valabind. It works and its maintained but you can distribute your r2bindgen inside this repo and providw more bindings to compare and let people be more confused about whih bindings use :D
