### ISSUE TITLE
When to update?

### ISSUE THREAD

**Issue by Resery** [radareorg/radare2-bindings#237]
I encountered a bug when using radare2-5.7.4-python-bindings. I want to use the command "iE" to get the export table. But the output missed something. But when I use radare2-5.8.8 the output is normal.
Finally I solved the problem by replacing "python3/site-packages/libr/libr_core.so(version 5.7.4)" with "/usr/lib/libr_core.so.5.8.8"

missed output:
![image](https://github.com/radareorg/radare2-bindings/assets/50428593/cfd4ed16-97cf-4ed6-9489-828b46c3e494)

normal output:
![image](https://github.com/radareorg/radare2-bindings/assets/50428593/48c45c1a-f52b-481b-932c-f591ad2c7b37)

**Comment by wtdcode** [comment]
This is due to your loading libraries from your systems instead of wheel shipped ones.

**Comment by Resery** [comment]
我英文表达有问题。我用中文重新描述下。这个问题是我通过 pip install 5.7.4 版本，通过 python 调 "iEj' 命令他有一段打印不出来，但是我将系统中的 libr_core 库（5.8.8）拷贝到 python3/site-packages/libr/ 下替换掉原本的 5.7.4 版本就可以正常打印了。您应该是中国人，所以我用中文回答了。

**Comment by wtdcode** [comment]
> 我英文表达有问题。我用中文重新描述下。这个问题是我通过 pip install 5.7.4 版本，通过 python 调 "iEj' 命令他有一段打印不出来，但是我将系统中的 libr_core 库（5.8.8）拷贝到 python3/site-packages/libr/ 下替换掉原本的 5.7.4 版本就可以正常打印了。您应该是中国人，所以我用中文回答了。

这样的话看起来是很久没有release了，时间有限，我找时间看看为什么自动release break了。

It looks like not having a release for a long time due to my lacking time. I could have a look why the release workflow fails later.

**Comment by trufae** [comment]
Yeah will be good to check this repo before the release but i was actually planing to do it after the release because enotime and its already quite delayed
